### ISSUE TITLE
Classity.py error

### ISSUE THREAD

**Issue by Tanuja-Sawant** [mortcanty/CRCPython#2]
I've been trying to run classify.py . However, it gives me the following error:
Traceback (most recent call last):
  File "classify.py", line 302, in <module>
    main()
  File "classify.py", line 95, in main
    classid = feature.GetField('CLASS_ID')
  File "/home/fay/anaconda2/lib/python2.7/site-packages/osgeo/ogr.py", line 3282, in GetField
    raise ValueError("Illegal field requested in GetField()")
ValueError: Illegal field requested in GetField()

could you please help me fix this?
Thank you

**Comment by mortcanty** [comment]
Sorry, I seem to have missed the GitHub notification on this issue. If it is still a problem, please send me a sample image for classification and the training shapefiles which reproduce the error so I can try to debug.

**Comment by tanujasawant** [comment]
That's fine, I figured out a solution then, thanks! :)

**Comment by jvidin** [comment]
@Tanuja-Sawant What was that ? Same error here - cant figure out it yet
